### ISSUE TITLE
搜索结果文字 对应 中英文官网

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#10]
现在官网准备做成中英文两个版本，在搜索的时候会对应的detail页面也是中英文两个版本。

@adam-chuan @nixiaoya 需要设计一下中英文页面，还有和官网的外包对接一下

@kandicelk 和张龙那边要一下 所有数据库的中英文翻译

**Comment by nixiaoya** [comment]
detail 页面是指我们的二级检索页还是各库的落地页 @vincentweiss

**Comment by vincentweiss** [comment]
是指目前架构中的第三个页面（第二层结果页，1=>2=>_`3`_=>4), 还有Blast功能相关的页面 @nixiaoya

**Comment by nixiaoya** [comment]
好的，页面是二级检索的结果页和 blast 相关的页面

下周拟完成相应的开发，并和外包方进行沟通

**Comment by nixiaoya** [comment]
所有页面，除去宣传组未提供的二级结果页的翻译文本，都已实现了中英文双语

根据浏览器本地语言类型，自动识别，并显示为对应文本

暂未提供手动语种的按钮

**Comment by nixiaoya** [comment]
已添加手动切换语言按钮

已实现所有页面模板的中英文，及项目简介的双语

未实现数据库内部数据的中英文

issue close
