### ISSUE TITLE
ICGC detail 结果页面 链接  

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#12]
ICGC 链接 可以更换成 https://icgcportal.genomics.cn/ @adam-chuan 

![icgc link](https://cloud.githubusercontent.com/assets/3094890/19877839/9ebfb60e-a01d-11e6-984d-c05826456867.png)

**Comment by nixiaoya** [comment]
@guonannan  小楠，ICGC 的链接调整下，改为国内的镜像站：https://icgcportal.genomics.cn, 这个是写在 restore_all.py 脚本中的。

**Comment by nixiaoya** [comment]
链接已调整，待同步上线

issue closed
