### ISSUE TITLE
#搜索结果# Hit DB 

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#15]
http://172.17.10.21/search/?q=a 结果只有部分数据库（除了DHGV），如果是超时 最好能返回一个 {loading} @nixiaoya @guonannan @adam-chuan 

![search3](https://cloud.githubusercontent.com/assets/3094890/20209032/f56aa560-a82c-11e6-91c3-33a8b2d06760.png)

**Comment by nixiaoya** [comment]
已处理

issue close
