### ISSUE TITLE
#gbrowser ensemble# GET error

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#16]
我这里有报错 ，你们可以试试 @duwensi @nixiaoya 
![browser](https://cloud.githubusercontent.com/assets/3094890/20463546/65cb63e0-af70-11e6-9e91-804cce20111a.png)

**Comment by duwensi** [comment]
![image](https://cloud.githubusercontent.com/assets/8371027/20468262/d0d46f9c-afcf-11e6-80ab-868577b89ecf.png)
That is the reason.

**Comment by nixiaoya** [comment]
![qq 20161121100859](https://cloud.githubusercontent.com/assets/10753981/20468522/86b0c174-afd2-11e6-9af2-e9faf3789b1d.png)
![qq 20161121100905](https://cloud.githubusercontent.com/assets/10753981/20468525/8926f194-afd2-11e6-89b1-16f9e27ac161.png)
确认为 ensembl 的证书问题，需要我们和 ensembl 官方进行邮件沟通吗？

**Comment by vincentweiss** [comment]
可以邮件里和他们沟通一下看看

**Comment by nixiaoya** [comment]
@shenwiyn  沈老师抽空今天邮件联系下 ensembl 官方，告知下他们证书过期的事情，看看他们打算怎么处理

**Comment by ghost** [comment]
已经邮件回复。
![20161121113744](https://cloud.githubusercontent.com/assets/12521320/20469937/00738f6c-afdf-11e6-877b-0b42bfa63e3b.png)

**Comment by nixiaoya** [comment]
今天查看 BiomiGo 的 job 页时，发现响应数据已经正常

**Comment by ghost** [comment]
Ensembl已经更新它们的证书，现api恢复正常。
![qq 20161124091720](https://cloud.githubusercontent.com/assets/12521320/20583682/0a307872-b227-11e6-9a94-5db729b11706.png)
