### ISSUE TITLE
#bug# 二级结果页 Nav自适应

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#2]
![bugs](https://cloud.githubusercontent.com/assets/3094890/19431921/eb23b4ce-948c-11e6-8e4c-cfa8defd1d49.png) @nixiaoya

**Comment by nixiaoya** [comment]
@adam-chuan  请查看下二级结果页的响应式

**Comment by adam-chuan** [comment]
内网的页面已经修改！

**Comment by nixiaoya** [comment]
![zty j i 5psp0 1vv fa i](https://cloud.githubusercontent.com/assets/10753981/19503050/a8349d88-95e3-11e6-8c09-49aac3eb35b4.png)

其他的二级模板页页存在相同的问题，请一并修改 @adam-chuan

**Comment by nixiaoya** [comment]
内网页面自适应，显示错位的问题已经处理，issue close
