### ISSUE TITLE
Expected value

### ISSUE THREAD

**Issue by ghost** [CNGB-DC/Biomigo#4]
blast 期望值（Expected value），这一参数控制搜索的灵敏度 (search sensitivity)，默认值是10.0。建议在“Expectation Value”已有值基础上增加"10.0"的选项值。

**Comment by nixiaoya** [comment]
关于 blast 参数调整的问题，可以整理成文档之后，上传到这里 @shenwiyn 

除了调整已有参数外，可能还需要新增一些参数，整理成文档后方便回溯

**Comment by nixiaoya** [comment]
新参数已在测试版中新增，稍后会同步到线上。
issue closed
