### ISSUE TITLE
"other parameters"的可填写框

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#5]
https://github.com/CNGB-DC/Biomigo/blob/master/Biomigo_blast_parameter.md Blast可以在这些参数的基础上 添加多一项"other parameters"的可填写框，供用户填写此外的参数值 @shenwiyn

**Comment by nixiaoya** [comment]
如果需要让用户可以自定义命令行参数，需要重新调整前后端和blast server 端的代码

是否必须在 1.1 中完成该功能？如果参数不可控的情况下，我们需要校验用户的自定义参数或是响应在参数错误的情况下，blast 的异常信息

@shenwiyn  沈老师看看其他站点是否有类似的自定义参数

**Comment by vincentweiss** [comment]
主要是考虑到1.1版本的参数是否已经完整覆盖，让用户在已有可选参数的基础上 添加新的参数。如果1.1版本来不及的话，可以直接挪到2.0版本上实现。 @shenwiyn 我记得其他站点应该是没有这个功能的，你可以再看看。

**Comment by ghost** [comment]
1. 我们已经把blast常用的参数以下拉框选择的模式整合到了Biomigo blast上，相对常用参数而言是比较完整的了。
2. 其他站点大多只有2到3个可自定义参数，这些可自定义参数我们已经包含在内，而且是以下拉框的可选模式呈现给用户。
3. 其他站点多数以 blastall 作为后台，部分参数以及用法与我们用的 blast+ 有区别。Biomigo blast 参数完整覆盖，后续可考虑再增加2到3个参数，相关用法我会持续更新。
