### ISSUE TITLE
Blast help document

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#6]
Blast help document 需要根据1.1最新的Blast参数 做好调整 @shenwiyn

**Comment by nixiaoya** [comment]
@shenwiyn 需要整理下新参数的英文文档，并联系 @adam-chuan  提交到 [blast文档](http://172.17.10.21/search/blast/document/) 页面上

**Comment by nixiaoya** [comment]
@shenwiyn Blast Document 页面调整完成后，反馈回这里

**Comment by ghost** [comment]
Blast Document has been modified to complete in dev version.

**Comment by nixiaoya** [comment]
调整已确认，待同步上线。

Issue closed
