### ISSUE TITLE
研究院数据库的接口更新

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#7]
研究院数据库的搜索功能有更新（包括DISSECT），需要更新一下接口，避免有部分数据没法检索到。

**Comment by vincentweiss** [comment]
能否设计一个"通用"的API约定，因为研究院的搜索关键词 可能随着开发会不断更新，例如HMD目前只有phenotype和gene，假设二期要加入sample 或者其他关键词。看能否在将搜索结果作为一个对象，每次更新搜索关键词，这个对象都会更新结果 并返回到 Biomigo 中解析。 @nixiaoya 需要和惠海讨论一下，避免每次都要人肉更新

**Comment by nixiaoya** [comment]
好的，我会和惠海沟通

其实现在 api 已经是开放的。我们在请求的时候，并未指定查询字段，都是之前刚开发的时候，大家不熟悉数据，手动约定的字段

各 api 可以复用各站的站内检索，根据各站的实际情况，来查询各自的字段

**Comment by vincentweiss** [comment]
ok, 那应该就没问题了 :) 在1.1版本里将其修复一下，另外DHGV的网站暂时是关闭的（服务器的性能不够），可以先不返回该网站的搜索结果

**Comment by nixiaoya** [comment]
好的，线上的 Biomigo 会关闭对 DHGV api 的访问

**Comment by nixiaoya** [comment]
现在研究院的 3 个数据库：PIRD, HMD, GDRD 已经更新了 api 接口

响应的数据内容和在各库本站检索的内容一致

**Comment by nixiaoya** [comment]
研究院 3 个数据库接口已完成调整，现检索结果和各站点本身的检索结果一致

Issue closed.
