### ISSUE TITLE
#GDRD# 搜索结果 （页面 2 => 3）

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#8]
http://db.cngb.org/search/?q=a
http://db.cngb.org/search/detail/?q=a&db=GDRD

![1](https://cloud.githubusercontent.com/assets/3094890/19714455/d1e86bbc-9b80-11e6-905a-960348aabd40.png)
![2](https://cloud.githubusercontent.com/assets/3094890/19714457/d709a2b4-9b80-11e6-927c-05327aca6149.png)

**Comment by nixiaoya** [comment]
一级检索页和二级检索页数据不匹配的问题已修复

二级检索页到详情信息页链接错误的问题，正在由 惠海 进行处理

**Comment by nixiaoya** [comment]
所有问题均已修复

issue close
