### ISSUE TITLE
#GDRD# 搜索结果 (页面 3 => 4)

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/Biomigo#9]
- 从搜索引擎跳转的情况
  http://db.cngb.org/search/detail/?q=a&db=GDRD
  http://db.cngb.org/gdrd/variation/10%3A101567988%3AT%3AA/ 
- 直接在GDRD网站上搜索的情况
  http://db.cngb.org/gdrd
  http://db.cngb.org/gdrd/variation/57e1f7a24adc8ea51ecb2710/

只有在本站搜索得到的url是正确的

@duwensi @nixiaoya

**Comment by nixiaoya** [comment]
一级检索页和二级检索页数据不匹配的问题已修复

二级检索页到详情信息页链接错误的问题，正在由 惠海 进行处理

**Comment by nixiaoya** [comment]
返回的 Url 异常问题，已经处理完毕

issue closed
